---
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.6

workflows:
  version: 2
  ci:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: benjlevesque/pr-comment
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-workflow:
          filters:
            branches:
              ignore: master
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
      - orb-tools/trigger-integration-workflow:
          filters:
            branches:
              only: master
          name: trigger-integration-master
          requires:
            - orb-tools/publish-dev
          tag: master
  cd:
    jobs:
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/
          name: dev-promote-patch
          orb-name: benjlevesque/pr-comment
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/
          name: dev-promote-minor
          orb-name: benjlevesque/pr-comment
          release: minor
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
          name: dev-promote-major
          orb-name: benjlevesque/pr-comment
          release: major
